'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const CATS=['Study','Time Management','Discipline','Communication','Habits','Friends','Family','Money','Technology','Personal Growth','Other'];
const Q={Morning:['Every moment gives you another chance to choose differently.','A calm morning is a good place to begin again.','Small choices become habits.','Start gently; direction matters more than speed.','Today does not need to repeat yesterday.','Notice first. Everything else follows.','One honest look forward is enough for now.','Clarity grows in quiet minutes.','Begin with what you can control.','Learning is a quiet kind of progress.','Let the morning be lighter than your worries.','Choose one thing to do well today.','Growth begins when you honestly look at what happened.'],
Afternoon:['Pause. Reflect. Learn.','You can adjust course at any hour.','Steady effort beats perfect effort.','A small correction now saves a large one later.','Focus is a choice you can make again.','Progress is often quiet.','Take a breath; the rest of the day is still open.','What you learn today outlasts what you regret.','Be patient with the person you are becoming.','Attention is worth protecting.','Understanding comes before improvement.','Slow down enough to see clearly.','Every day holds room for a better decision.'],
Evening:['Learn from yesterday without carrying its weight.','Let the day settle; keep only what taught you something.','You do not have to write today to grow today.','Reflection is kindness toward your future self.','Honest is not the same as harsh.','What happened is information, not a verdict.','Rest is part of learning.','Look back gently, then look ahead.','A lesson learned is never wasted time.','Let go of what you cannot change; keep what you can use.','Evenings are for understanding, not judging.','You are allowed to be unfinished.','Awareness is already a step forward.'],
Night:['Rest well; tomorrow is a new page.','The day is done. What remains is what you learned.','Be gentle with yourself tonight.','Nothing needs solving before sleep.','Quiet minds see clearly in the morning.','Let the night carry the noise away.','You did what you could with what you knew.','Peace is a lesson too.','Sleep is a form of self-respect.','Carry the lesson, leave the weight.','Tomorrow will meet you as you are.','Stillness helps understanding settle.','Even slow days move you forward.']};
/* IndexedDB */
const DB=new Promise((ok,no)=>{const q=indexedDB.open('karma',1);q.onupgradeneeded=()=>q.result.createObjectStore('e',{keyPath:'id'});q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});
const tx=async(m,f)=>{const d=await DB;return new Promise((ok,no)=>{const t=d.transaction('e',m),q=f(t.objectStore('e'));t.oncomplete=()=>ok(q&&q.result);t.onerror=()=>no(t.error)})};
const all=()=>tx('readonly',s=>s.getAll()).then(a=>a.sort((x,y)=>y.at.localeCompare(x.at)));
const put=e=>tx('readwrite',s=>s.put(e)),del=id=>tx('readwrite',s=>s.delete(id)),clr=()=>tx('readwrite',s=>s.clear());
const one=id=>tx('readonly',s=>s.get(id));
/* helpers */
const toast=m=>{const t=$('#toast');t.textContent=m;t.className='s';setTimeout(()=>t.className='',3500)};
const D=e=>new Date(e.at),fd=e=>D(e).toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'}),fw=e=>D(e).toLocaleDateString(undefined,{weekday:'long'}),ft=e=>D(e).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
const b2d=b=>new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(b)});
const d2b=d=>fetch(d).then(r=>r.blob());
const dl=(blob,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000)};
const period=h=>h>=5&&h<12?'Morning':h<17&&h>=12?'Afternoon':h>=17&&h<21?'Evening':'Night';
function quote(){const p=period(new Date().getHours()),l=Q[p];let last=+localStorage.kq??-1;if(isNaN(last))last=-1;let i;do{i=Math.floor(Math.random()*l.length)}while(i===last&&l.length>1);localStorage.kq=i;return l[i]}
/* Local reflection engine: uses only the user's own words (no external AI needed). */
const RULES=[[/phone|scroll|social media|youtube|game/i,'I let a distraction take over time I had planned for something else.','Having a plan is not enough; I also need to protect my focus.','Small distractions can use far more time than I expect.','I will put the distraction out of reach before I start.'],
[/late|deadline|forgot|missed|procrastinat|delay/i,'I let time slip past something that mattered.','I realized that waiting made the task harder, not easier.','Starting early gives me room to handle surprises.','I will set a reminder and start the first small step right away.'],
[/said|shout|yell|argu|angry|rude|snapped|fight/i,'I reacted in the moment instead of responding thoughtfully.','I realized my words landed harder than I intended.','A short pause can change how a conversation ends.','I will pause and take one breath before I reply.'],
[/spent|bought|money|paid|wasted/i,'I made a spending decision without thinking it through.','I realized I decided quickly and only later noticed the cost.','A short wait before spending helps me choose well.','I will wait 24 hours before buying anything non-essential.']];
function reflect(t,title){const s=(t.match(/[^.!?\n]+[.!?]?/)||[t])[0].trim().slice(0,220);const r=RULES.find(x=>x[0].test(t+' '+title));
return{whatHappened:s?`I recorded: "${s}"`:`I recorded "${title}".`,myMistake:r?r[1]:`The decision or action I described in "${title||'this entry'}" did not go the way I wanted.`,realization:r?r[2]:'I realized that looking honestly at what happened helps me understand it.',lesson:r?r[3]:'Noticing a mistake early makes it easier to handle differently next time.',nextTime:r?r[4]:'Next time, I will pause and ask what I want the outcome to be before I act.',createdAt:new Date().toISOString(),generated:'local'}}
const url=b=>URL.createObjectURL(b);
const empty=m=>`<div class="empty">${m}</div>`;
/* views */
const V={};let list=[];
V.home=async()=>{const n=new Date();return`<div class="card"><div class="time"><h1 style="margin:0;color:var(--tx)">${n.toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'})}</h1>${n.toLocaleDateString(undefined,{weekday:'long'})} · ${n.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</div></div>
<div class="card quote">“${esc(quote())}”</div><button class="big" onclick="location.hash='#new'">+ Record a mistake</button>
<div class="grid" style="margin-top:12px"><div class="card stat" style="background:#FEF3C7"><b>${list.length}</b><small>Mistakes</small></div><div class="card stat" style="background:#E0F2FE"><b>${list.filter(e=>e.reflection).length}</b><small>Realizations</small></div><div class="card stat" style="background:#DCFCE7"><b>${list.filter(e=>e.reflection?.lesson).length}</b><small>Lessons</small></div></div>
<h2>Recent mistakes</h2>${list.slice(0,4).map(card).join('')||empty('No mistakes recorded yet.<br>Your first reflection will appear here when you are ready.')}`};
const media=e=>[e.voice?'🎙':'',e.photos?.length?'📷':'',e.pdfs?.length?'📄':''].join(' ');
const card=e=>`<div class="card"><b>${e.fav?'★ ':''}${esc(e.title||'Untitled')}</b><div class="time">${fd(e)} · ${fw(e)} · ${ft(e)} ${media(e)}</div><p>${esc(e.text.slice(0,140))}${e.text.length>140?'…':''}</p><div class="row"><button onclick="location.hash='#entry/${e.id}'">Open</button><button onclick="location.hash='#new/${e.id}'">Edit</button><button onclick="fav('${e.id}')">${e.fav?'Unfavorite':'Favorite'}</button><button class="d" onclick="rm('${e.id}')">Delete</button></div></div>`;
const hay=e=>[e.title,e.text,e.voice?.transcript,e.category,e.reflection?.realization,e.reflection?.lesson,fd(e),fw(e)].join(' ').toLowerCase();
V.mistakes=async()=>{const q=(sessionStorage.q||'').toLowerCase(),c=sessionStorage.c||'',f=sessionStorage.f;const r=list.filter(e=>(!q||hay(e).includes(q))&&(!c||e.category===c)&&(!f||e.fav));
return`<h1>Mistakes</h1><input id="q" placeholder="Search everything…" value="${esc(sessionStorage.q||'')}" oninput="sessionStorage.q=this.value;go(true)"><select onchange="sessionStorage.c=this.value;go()"><option value="">All categories</option>${CATS.map(x=>`<option ${x===c?'selected':''}>${x}</option>`).join('')}</select><label><input type="checkbox" style="width:auto" ${f?'checked':''} onchange="sessionStorage.f=this.checked?1:'';go()"> Favorites only</label>${r.map(card).join('')||empty(list.length?'Nothing matches your search.':'No mistakes recorded yet.<br>Your first reflection will appear here when you are ready.')}`};
V.realize=async()=>{const r=list.filter(e=>e.reflection);return`<h1>Realize</h1>${r.map(e=>`<div class="card" onclick="location.hash='#entry/${e.id}'" style="cursor:pointer"><span class="time">${fd(e)} · ${ft(e)}</span><span class="tag">MISTAKE</span><b>${esc(e.title)}</b><span class="tag">REALIZATION</span>${esc(e.reflection.realization)}<span class="tag">LESSON</span>${esc(e.reflection.lesson)}<span class="tag">NEXT TIME</span>${esc(e.reflection.nextTime)}</div>`).join('')||empty('Your realizations will appear here after you record an experience.')}`};
V.diary=async()=>{if(!list.length)return`<h1>Diary</h1>`+empty('Your KARMA diary is empty.');const g={};list.forEach(e=>(g[fd(e)+'|'+fw(e)]??=[]).push(e));
return`<h1>Diary</h1><p class="time">Only days with an entry appear here.</p><div class="row noprint"><button onclick="window.print()">Export all as PDF</button></div>${Object.entries(g).map(([k,a])=>`<h3>${k.replace('|',' · ')}</h3>${a.map(e=>`<div class="card" onclick="location.hash='#entry/${e.id}'" style="cursor:pointer"><span class="time">${ft(e)} · Mistake recorded</span><br><b>${esc(e.title)}</b></div>`).join('')}`).join('')}`};
V.entry=async id=>{const e=await one(id);if(!e)return empty('Entry not found.');const r=e.reflection;
return`<img class="pr-logo" src="assets/logo.png" alt="KARMA"><h1>${esc(e.title)}</h1><div class="time">${fd(e)}<br>${fw(e)} · ${ft(e)}${e.category?' · '+esc(e.category):''}</div>
<div class="card mine"><span class="tag">MISTAKE · WRITTEN BY ME</span><p style="white-space:pre-wrap">${esc(e.text)}</p></div>
${e.voice||e.photos?.length||e.pdfs?.length?`<div class="card"><span class="tag">ATTACHMENTS</span>${e.voice?`🎙 Voice<audio controls src="${url(e.voice.blob)}"></audio>${e.voice.transcript?`<p><small>Transcript (auto-generated)</small><br>${esc(e.voice.transcript)}</p>`:''}`:''}${(e.photos||[]).map(p=>`<img class="ph" src="${url(p.blob)}">`).join('')}${(e.pdfs||[]).map(p=>`<div>📄 <a target="_blank" href="${url(p.blob)}">${esc(p.name)}</a> (${(p.blob.size/1024).toFixed(0)} KB)</div>`).join('')}</div>`:''}
${r?`<div class="card ai"><span class="tag">GENERATED REFLECTION</span>${[['WHAT HAPPENED','whatHappened'],['MY MISTAKE','myMistake'],['REALIZATION','realization'],['LESSON','lesson'],['NEXT TIME','nextTime']].map(([l,k])=>`<span class="tag">${l}</span>${esc(r[k])}`).join('')}</div>`:''}
<div class="row noprint"><button onclick="window.print()">Export this entry as PDF</button><button onclick="location.hash='#new/${e.id}'">Edit</button><button onclick="fav('${e.id}')">${e.fav?'Unfavorite':'Favorite'}</button><button class="d" onclick="rm('${e.id}')">Delete</button></div>`};
let draft;
V.new=async id=>{const old=id&&await one(id);draft=old?{...old,photos:[...(old.photos||[])],pdfs:[...(old.pdfs||[])]}:{id:uid(),photos:[],pdfs:[],voice:null};window.old=old;const d=draft;
return`<h1>${old?'Edit mistake':'Record a mistake'}</h1><div class="card"><label>Title</label><input id="t" value="${esc(d.title)}"><label>What happened?</label><textarea id="x">${esc(d.text)}</textarea><label>Category (optional)</label><select id="c"><option value="">None</option>${CATS.map(x=>`<option ${x===d.category?'selected':''}>${x}</option>`).join('')}</select><label>Additional notes (optional)</label><textarea id="n" style="min-height:70px">${esc(d.notes)}</textarea></div>
<div class="card"><b>🎙 Voice</b><div class="row"><button onclick="rec('start')">Start</button><button onclick="rec('pause')">Pause</button><button onclick="rec('resume')">Resume</button><button onclick="rec('stop')">Stop</button><button class="d" onclick="draft.voice=null;$('#va').innerHTML=''">Delete</button></div><div id="va">${d.voice?`<audio controls src="${url(d.voice.blob)}"></audio>`:''}</div><small id="rs"></small>
<label>Voice transcript (type or paste; not auto-generated unless a speech service is connected)</label><textarea id="tr" style="min-height:60px">${esc(d.voice?.transcript)}</textarea></div>
<div class="card"><b>📷 Photos</b><input type="file" accept="image/*" multiple onchange="addF(this,'photos')"><div id="pl"></div><b>📄 PDFs</b><input type="file" accept="application/pdf" multiple onchange="addF(this,'pdfs')"><div id="dl"></div></div>
<div class="row"><button class="big" onclick="save()">Save mistake</button><button onclick="history.back()">Cancel</button></div>`};
let mr,chunks=[];
window.rec=async a=>{try{if(a==='start'){const s=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mr=new MediaRecorder(s);mr.ondataavailable=e=>chunks.push(e.data);mr.onstop=()=>{s.getTracks().forEach(t=>t.stop());const b=new Blob(chunks,{type:mr.mimeType});draft.voice={blob:b,transcript:draft.voice?.transcript||''};$('#va').innerHTML=`<audio controls src="${url(b)}"></audio>`;$('#rs').textContent='Recording saved to this entry.'};mr.start();$('#rs').textContent='Recording…'}else if(mr){a==='pause'&&mr.state==='recording'&&mr.pause();a==='resume'&&mr.state==='paused'&&mr.resume();a==='stop'&&mr.state!=='inactive'&&mr.stop()}}catch(e){toast('Microphone unavailable. Please allow microphone access in your browser settings.')}};
window.addF=async(i,k)=>{for(const f of i.files){if(f.size>25e6){toast(f.name+' is larger than 25 MB.');continue}draft[k].push({id:uid(),name:f.name,blob:f})}i.value='';drawF()};
const drawF=()=>{$('#pl').innerHTML=draft.photos.map((p,i)=>`<div><img class="ph" style="max-height:140px" src="${url(p.blob)}"><button onclick="draft.photos.splice(${i},1);drawF()">Remove</button></div>`).join('');$('#dl').innerHTML=draft.pdfs.map((p,i)=>`<div>📄 <a target="_blank" href="${url(p.blob)}">${esc(p.name)}</a> ${(p.blob.size/1024).toFixed(0)} KB <button onclick="draft.pdfs.splice(${i},1);drawF()">Remove</button></div>`).join('')};
window.save=async()=>{const t=$('#t').value.trim(),x=$('#x').value;if(!t&&!x.trim())return toast('Add a title or describe what happened first.');const now=new Date().toISOString();
const e={...draft,title:t||x.trim().slice(0,50),text:x,notes:$('#n').value,category:$('#c').value,updatedAt:now,at:old_at(),createdAt:draft.createdAt||now};
if(e.voice)e.voice.transcript=$('#tr').value;
if(!e.reflection||e.text!==window.old?.text)e.reflection=reflect(e.text+' '+e.notes,e.title);
try{await put(e);toast('Mistake saved.');location.hash='#entry/'+e.id}catch(er){toast('Could not save. Your browser storage may be full.')}};
const old_at=()=>window.old?.at||new Date().toISOString();
window.fav=async id=>{const e=await one(id);e.fav=!e.fav;await put(e);go()};
window.rm=async id=>{if(confirm('Delete this entry permanently?')){await del(id);location.hash='#mistakes';go()}};
/* Data */
V.data=async()=>{const c=k=>list.reduce((n,e)=>n+(k==='v'?(e.voice?1:0):(e[k]||[]).length),0);return`<h1>Data</h1>
<div class="card"><b>Export KARMA data</b><p>Saves every entry, reflection and attachment into one file you can keep anywhere.</p><button class="p" onclick="exp()">Export KARMA Data</button></div>
<div class="card"><b>Import KARMA data</b><p>Choose a <code>.karma.json</code> backup.</p><input type="file" accept=".json,.karma.json" onchange="prev(this)"><div id="ip"></div></div>
<div class="card"><b>Settings</b><p class="time">${list.length} entries · ${c('photos')} photos · ${c('v')} voice · ${c('pdfs')} PDFs stored on this device only.</p><button class="d" onclick="wipe()">Delete all data</button></div>`};
window.exp=async()=>{try{const en=await Promise.all(list.map(async e=>({...e,voice:e.voice&&{transcript:e.voice.transcript,data:await b2d(e.voice.blob)},photos:await Promise.all((e.photos||[]).map(async p=>({id:p.id,name:p.name,data:await b2d(p.blob)}))),pdfs:await Promise.all((e.pdfs||[]).map(async p=>({id:p.id,name:p.name,data:await b2d(p.blob)})))})));
dl(new Blob([JSON.stringify({format:'karma-backup',version:1,exportedAt:new Date().toISOString(),entries:en})],{type:'application/json'}),`KARMA_Backup_${new Date().toISOString().slice(0,10)}.karma.json`);toast('Your KARMA data has been exported successfully.')}catch(e){toast('Export failed. Please try again.')}};
let pend;
window.prev=async i=>{const f=i.files[0];if(!f)return;try{const j=JSON.parse(await f.text());if(j.format!=='karma-backup'||j.version!==1||!Array.isArray(j.entries))throw 0;pend=j;const n=k=>j.entries.reduce((a,e)=>a+(k==='v'?(e.voice?1:0):(e[k]||[]).length),0);
$('#ip').innerHTML=`<h3>Import KARMA data</h3><p>${j.entries.length} mistakes<br>${j.entries.filter(e=>e.reflection).length} realizations<br>${j.entries.filter(e=>e.reflection?.lesson).length} lessons<br>${n('photos')} photos · ${n('v')} voice recordings · ${n('pdfs')} PDFs</p><label><input type="radio" name="m" value="merge" checked style="width:auto"> Merge with existing data (skips duplicates)</label><br><label><input type="radio" name="m" value="replace" style="width:auto"> Replace existing data</label><div class="row"><button onclick="$('#ip').innerHTML='';pend=null">Cancel</button><button class="p" onclick="imp()">Import</button></div>`}catch(e){toast('Unable to import this file. Please select a valid KARMA backup.')}};
window.imp=async()=>{const m=document.querySelector('[name=m]:checked').value;if(m==='replace'&&!confirm('This will replace your current KARMA data. Export a backup first if you want to keep it.'))return;
try{const ex=new Set(list.map(e=>e.id));if(m==='replace')await clr();for(const e of pend.entries){if(m==='merge'&&ex.has(e.id))continue;await put({...e,voice:e.voice&&{transcript:e.voice.transcript,blob:await d2b(e.voice.data)},photos:await Promise.all((e.photos||[]).map(async p=>({id:p.id,name:p.name,blob:await d2b(p.data)}))),pdfs:await Promise.all((e.pdfs||[]).map(async p=>({id:p.id,name:p.name,blob:await d2b(p.data)})))})}toast('Your KARMA data has been restored successfully.');go()}catch(e){toast('Import failed. Your existing data was not changed by the failed step.')}};
window.wipe=async()=>{if(confirm('Delete ALL KARMA data on this device? This cannot be undone.')&&confirm('Really delete everything? Export a backup first if unsure.')){await clr();toast('All data deleted.');go()}};
/* router */
const NAV=[['home','Home'],['mistakes','Mistakes'],['realize','Realize'],['diary','Diary'],['data','Data']];
window.go=async keep=>{const[h,id]=(location.hash.slice(1)||'home').split('/');list=await all();const v=V[h]||V.home;$('#nav').innerHTML=NAV.map(([k,l])=>`<a href="#${k}" class="${k===h?'on':''}">${l}</a>`).join('');
const y=scrollY,f=document.activeElement?.id==='q';$('#app').innerHTML=await v(id);if(keep){scrollTo(0,y);if(f){const q=$('#q');q.focus();q.setSelectionRange(q.value.length,q.value.length)}}else scrollTo(0,0);drawF&&$('#pl')&&drawF()};
addEventListener('hashchange',()=>go());go();
